version: '3.8'

services:
  app:
    image: ghcr.io/mitchtalmadge/dev
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:redis

  redis:
    image: redislabs/rejson
    restart: unless-stopped